In [1]:
import numpy as np
print(np.__version__)

2.5.1


In [2]:
lista = [1,2,3,4]
type(lista)

list

In [3]:
array = np.array([1,2,3,4])
type(array)

numpy.ndarray

In [4]:
array*2

array([2, 4, 6, 8])

In [6]:
lista = [1,2,3,4]
arr_lista = np.array(lista)
print(arr_lista)
arr_lista.dtype

[1 2 3 4]


dtype('int64')

In [7]:
lista = [1,2,3,4]
arr_lista = np.array(lista, dtype= 'float64')
print(arr_lista)
arr_lista.dtype

[1. 2. 3. 4.]


dtype('float64')

In [8]:
lista = [1,2,3,4]
arr_lista = np.array(lista)
print(arr_lista)
arr_lista.dtype

[1 2 3 4]


dtype('int64')

In [9]:
arr_float = arr_lista.astype('float64')
print(arr_float)
arr_float.dtype

[1. 2. 3. 4.]


dtype('float64')

In [10]:
arr_float = arr_lista.astype('str')
print(arr_float)
arr_float.dtype

['1' '2' '3' '4']


dtype('<U21')

In [12]:
#scalar
scalar = np.array(50)
print(scalar)
print(type(scalar))

50
<class 'numpy.ndarray'>


In [13]:
vector = np.array([1,2,3,4])
print(vector.ndim)

1


In [18]:
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matriz.ndim)

2


In [21]:
np.zeros((5,6,2),dtype= 'int64')

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])